{% set name = "libva-utils" %}
{% set version = "2.7.0" %}
{% set version_split = version.split('.') %}
{% set version_pin = version_split[0] + '.' + version_split[1] %}

# Follow instructions here
# https://gist.github.com/Brainiarc7/eb45d2e22afec7534f4a117d15fe6d89

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/{{ version }}.tar.gz
  fn: libva-utils-{{ version }}.tar.gz
  sha256: bcb0d4c0efadf9600dd5064ee8e2e08e8d1bc7307e829e39d0f8206016a3fda2

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
  host:
    - libva {{ version_pin }}
    - intel-vaapi-driver

test:
  commands:
    # We can't actually run the bare vainfo command since it requires
    # A display which circleci doesn't have
    - vainfo --help

about:
  home: https://github.com/intel/libva
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Libva is an implementation for VA-API (Video Acceleration API)
  description: |
    libva-utils is a collection of utilities and examples to exercise VA-API in
    accordance with the libva project. --enable-tests (default = no) provides a
    suite of unit-tests based on Google Test Framework. A driver implementation
    is necessary to properly operate.

extra:
  recipe-maintainers:
    - hmaarrfk
