{% set name = "libva-utils" %}
{% set version = "2.22.0" %}
{% set major_minor_version = ".".join(version.split('.')[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 7b57615c130427ec134bb5d2b80af516ce5bb19a40e89b1dab46a0d59760d96c

build:
  skip: true  # [osx]
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ stdlib('cxx') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - meson
    - ninja
  host:
    - xorg-libx11  # [linux]
    - libdrm       # [linux]
    - wayland      # [linux]
    - libva {{ major_minor_version }}
    - intel-vaapi-driver  # [linux64]

test:
  commands:
    # We can't actually run the bare vainfo command without a display
    - vainfo --help

about:
  home: https://github.com/intel/libva-utils/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Libva is an implementation for VA-API (Video Acceleration API)
  description: |
    libva-utils is a collection of utilities and examples to exercise VA-API in
    accordance with the libva project. --enable-tests (default = no) provides a
    suite of unit-tests based on Google Test Framework. A driver implementation
    is necessary to properly operate.

extra:
  recipe-maintainers:
    - hmaarrfk
    - ehfd
