{% set name = "libva-utils" %}
{% set version = "2.16.0" %}
{% set major_minor_version = ".".join(version.split('.')[:2]) %}

# https://gist.github.com/Brainiarc7/eb45d2e22afec7534f4a117d15fe6d89
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 646c9bfff6a83504c48de2c786c9514ca30c5e916127faf00f143ef8147ee950

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make        # [unix]
  host:
    - libva {{ major_minor_version }}
    - intel-vaapi-driver

test:
  commands:
    # We can't actually run the bare vainfo command since it requires
    # A display which circleci doesn't have
    - vainfo --help

about:
  home: https://github.com/intel/libva-utils/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Libva is an implementation for VA-API (Video Acceleration API)
  description: |
    libva-utils is a collection of utilities and examples to exercise VA-API in
    accordance with the libva project. --enable-tests (default = no) provides a
    suite of unit-tests based on Google Test Framework. A driver implementation
    is necessary to properly operate.

extra:
  recipe-maintainers:
    - hmaarrfk
