{% set name = "libva-utils" %}
{% set version = "2.4.1" %}

# Follow instructions here
# https://gist.github.com/Brainiarc7/eb45d2e22afec7534f4a117d15fe6d89

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/{{ version }}.tar.gz
  fn: libva-utils-{{ version }}.tar.gz
  sha256: 4ab6faa6592ffe2d4817450f5453f3974b47441650e8f49e1a12497ce2a794ac
  patches:
    # https://github.com/intel/libva-utils/issues/153
    # https://github.com/intel/libva-utils/pull/152
    - 152-skip_vendor_intel_sfcsample.patch

build:
  skip: True  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
  host:
    - libva
    - intel-vaapi-driver

test:
  commands:
    # We can't actually run the bare vainfo command since it requires
    # A display which circleci doesn't have
    - vainfo --help

about:
  home: https://github.com/intel/libva
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Libva is an implementation for VA-API (Video Acceleration API)'
  description: |
    libva-utils is a collection of utilities and examples to exercise VA-API in
    accordance with the libva project. --enable-tests (default = no) provides a
    suite of unit-tests based on Google Test Framework. A driver implementation
    is necessary to properly operate.

extra:
  recipe-maintainers:
    - hmaarrfk
