travis:
  secure:
    BINSTAR_TOKEN: TbzbgO3836lFXmsbJVpsv/WfyoNv5F7icZ57W/b6HoNkTdNuHoSk049u5hq64fpBld92OpSLKhDPqFBBtFv0ipjOScdGarEJ9d57DfL5YmNuQOvvHKUXleg1MQ76UHVT5t+WrJjw24ub8jdD7d0y2y+tjErgvfZhkaw37SLH68xE/C24yZHMpaMgNFmdhwEbza8Y5HWfFKmgpbfUEjek8Ovq7UYbwvGwVJ07bvUUTTajBm72anY9WdcA11DQ1Wz154cGXzUARS38DFz/F/U4QPGVKEGf+NaFLwTa7vJBMzSj150aEnwKWFa16HUz1dfdGORrkHpllUzTmgk3zw80KTjGOHOb/54/U30j1Jdy/Fesdz41KUGYOyocX5NyfBOlOd3m/PfRoMPbJ1Nwd7zlhzOFM2L7OHdcmYshZrgr7yLICmEVz9ZAsIEvZ7Cd1IvQKMoK6tt7fFpTqu2iFcfuiE6L6JGI7vuDPTaX3hUdxBiY9I/7YWBzKeTfOsyf6ryLZniES5gQBQHh3hNpH8LIp2D8mCBxDpIEpwgGOgYzl3EZR7DFNP1iCNIzy/B9j4+KpsYnBtTfBlMUywGzecna94c6Dtvx9ikA+s3/rT2MwjZF/lH0jWzAwK5kXSWNKyMB5KdyMol/30DjkF+a0OTrShrOxg2b/Wr/gyswjcLt2Y8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
